[package]
name = "n-puzzle"
version = "0.1.0"
authors = ["Simon Galasso <simon.galasso@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulinalg = "0.4.2"